pes_competition_list:
    pattern:  /liste
    defaults: { _controller: "PesFrontBundle:Competition:index" }

pes_competition_show:
    pattern:  /{id}/show
    defaults: { _controller: "PesFrontBundle:Competition:show" }

pes_competition_new:
    pattern:  /new
    defaults: { _controller: "PesFrontBundle:Competition:new" }

pes_competition_create:
    pattern:  /create
    defaults: { _controller: "PesFrontBundle:Competition:create" }
    requirements: { _method: post }

pes_competition_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "PesFrontBundle:Competition:edit" }

pes_competition_update:
    pattern:  /{id}/update
    defaults: { _controller: "PesFrontBundle:Competition:update" }
    requirements: { _method: post|put }

pes_competition_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "PesFrontBundle:Competition:delete" }
    requirements: { _method: post|delete }
