pes_tournoi_list:
    pattern:  /liste
    defaults: { _controller: "PesFrontBundle:Tournoi:index" }

pes_tournoi_show:
    pattern:  /{id}/show
    defaults: { _controller: "PesFrontBundle:Tournoi:show" }

pes_tournoi_new:
    pattern:  /new
    defaults: { _controller: "PesFrontBundle:Tournoi:new" }

pes_tournoi_create:
    pattern:  /create
    defaults: { _controller: "PesFrontBundle:Tournoi:create" }
    requirements: { _method: post }

pes_tournoi_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "PesFrontBundle:Tournoi:edit" }

pes_tournoi_update:
    pattern:  /{id}/update
    defaults: { _controller: "PesFrontBundle:Tournoi:update" }
    requirements: { _method: post|put }

pes_tournoi_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "PesFrontBundle:Tournoi:delete" }
    requirements: { _method: post|delete }
