<?php

namespace Pes\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentaireNewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireNewsRepository extends EntityRepository
{
}
