<?php

namespace Pes\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
	public function lastNews() {
		return $this->createQueryBuilder('n')
			->orderBy('n.date', 'DESC')
			->setMaxResults(5)
			->getQuery()
			->getResult();
	}
}
