<?php

namespace Pes\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeCompetitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeCompetitionRepository extends EntityRepository
{
}
