<?php

namespace Proxies\__CG__\Pes\FrontBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Competition extends \Pes\FrontBundle\Entity\Competition implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNom($nom)
    {
        $this->__load();
        return parent::setNom($nom);
    }

    public function getNom()
    {
        $this->__load();
        return parent::getNom();
    }

    public function setAjout($ajout)
    {
        $this->__load();
        return parent::setAjout($ajout);
    }

    public function getAjout()
    {
        $this->__load();
        return parent::getAjout();
    }

    public function setDate($date)
    {
        $this->__load();
        return parent::setDate($date);
    }

    public function getDate()
    {
        $this->__load();
        return parent::getDate();
    }

    public function setResultat($resultat)
    {
        $this->__load();
        return parent::setResultat($resultat);
    }

    public function getResultat()
    {
        $this->__load();
        return parent::getResultat();
    }

    public function setTypeCompetition(\Pes\FrontBundle\Entity\TypeCompetition $typeCompetition)
    {
        $this->__load();
        return parent::setTypeCompetition($typeCompetition);
    }

    public function getTypeCompetition()
    {
        $this->__load();
        return parent::getTypeCompetition();
    }

    public function setTournoi(\Pes\FrontBundle\Entity\Tournoi $tournoi)
    {
        $this->__load();
        return parent::setTournoi($tournoi);
    }

    public function getTournoi()
    {
        $this->__load();
        return parent::getTournoi();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nom', 'ajout', 'date', 'resultat', 'typeCompetition', 'tournoi');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}